apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: regexicon
  annotations:
    github.com/project-slug: lorcanmcdonald/regexicon
spec:
  type: website
  lifecycle: experimental
  owner: Lorcan McDonald
