#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

"$DIR/script/build"

set +e
docker kill candidates
docker rm candidates
set -e

docker run \
  -p 3000:80 \
  -d \
  --rm \
  -ti \
  -v "$DIR/js/dist:/opt/service/js" \
  -v "$DIR/style:/opt/service/style" \
  --name candidates \
  lorcan/regex-candidates

pushd "$DIR/js"
webpack --progress --watch --mode=development
popd
