#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# shellcheck source=script/Prelude
source "$DIR/script/Prelude"

"$DIR/script/update"

set +e
docker kill candidates
docker rm candidates
set -e

docker run \
  -p 3000:80 \
  -d \
  -ti \
  -v "$DIR/js/dist:/opt/service/js" \
  -v "$DIR/style:/opt/service/style" \
  --name candidates \
  lorcan/regex-candidates

pushd "$DIR/js"
run_node "./node_modules/.bin/webpack" --progress --watch --mode=development
popd
