#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

"$DIR/script/update"

run_haskell() {
  set +u
  docker run \
      --rm \
      -ti \
      -v "$DIR/:/opt/build" \
      -v "$DIR/obj/cabal-sandbox:/opt/build/.cabal-sandbox" \
      -v "$DIR/obj/dist:/opt/build/dist" \
      -w /opt/build \
      lorcan/haskell-build:8.6 \
        $1 $2 $3 $4 $5 $6 $7 $8 $9
  set -u
}

run_haskell sh -c 'PATH=$PATH:/opt/build/bin cabal v2-test'
