#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# shellcheck source=script/Prelude
source "$DIR/script/Prelude"

"$DIR/script/update"
GHC_VERSION=8.8.3

run_haskell sh -c 'PATH=$PATH:/opt/build/bin cabal new-update && TASTY_QUICKCHECK_TESTS=20 cabal new-test --enable-coverage'

run_haskell ls /opt/build/dist-newstyle/build/x86_64-linux/ghc-$GHC_VERSION/Matching-0.1.0.0/hpc/vanilla/tix/test-matching/

run_haskell hpc markup \
  /opt/build/dist-newstyle/build/x86_64-linux/ghc-$GHC_VERSION/Matching-0.1.0.0/hpc/vanilla/tix/test-matching/test-matching.tix \
  "--destdir=/opt/build/dist-newstyle/build/x86_64-linux/ghc-$GHC_VERSION/Matching-0.1.0.0/hpc/vanilla/html/Matching-0.1.0.0" \
  "--hpcdir=dist-newstyle/build/x86_64-linux/ghc-$GHC_VERSION/Matching-0.1.0.0/hpc/vanilla/mix/Matching-0.1.0.0" \
  "--hpcdir=dist-newstyle/build/x86_64-linux/ghc-$GHC_VERSION/Matching-0.1.0.0/hpc/vanilla/mix/test-matching"

run_haskell sh -c 'find dist-newstyle -name "*.mix" | xargs rm'
