#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

run_haskell() {
  set +u
  docker run \
      --rm \
      -v "$DIR/:/opt/build" \
      -v "$DIR/obj/home:/root/" \
      -v "$DIR/obj/cabal-sandbox:/opt/build/.cabal-sandbox" \
      -v "$DIR/obj/dist:/opt/build/dist" \
      -w /opt/build \
      haskell:8.0 \
        $1 $2 $3 $4 $5 $6 $7 $8 $9
  set -u
}

run_haskell cabal sandbox init
run_haskell sh -c "cabal update && cabal install --dependencies-only"
run_haskell cabal build

pushd "$DIR/js"
npm install
"$DIR/js/node_modules/.bin/webpack" \
  --config "$DIR/js/webpack.config.js" \
  --mode=production

popd
docker build -t lorcan/regex-candidates --file "$DIR/containers/service.Dockerfile" "$DIR"
